
#ifndef TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_H_
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_H_

/*
 *******************************************************************************
 * License
 * (C) Copyright 2017
 *******************************************************************************
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications according to the supply agreement.
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software.
 * 2. This notice may not be removed or altered from any source distribution.
 *
 * DISCLAIMER OF WARRANTY/LIMITATION OF REMEDIES: this software is provided
 * "AS IS", with no express or implied warranties of any kind, including,
 * but not limited to, any implied warranties of merchantability or
 * fitness for any particular purpose or warranties against infringement
 * of any proprietary rights of a third party.
 *
 * Supplier will not be liable for any consequential, incidental, or
 * special damages, or any other relief, or for any claim by any third party,
 * arising from your use of this Software.
 *
 */

/**
 * Author
 * TommRo Software Department
 */

/*******************************************************************************
 * includes
 ******************************************************************************/
#include "TOMMROC.h"

#if defined (TOMMRO_C_ENV_ENVIRONMENT_IS_ARM)

#include "env/tommRoCTemplateEnv.h"

#if defined (__TOMMROC_TEMPLATE_ARM_HAL_DRIVER_IS_USED__)
#include "bus/uart/tommRoCHwTemplateBusUARTDEF.h"
#if defined (__TOMMROC_HW_TEMPLATE_BUS_UART_DEF_AT_LEAST_ONE_UART_IS_USED__) || defined (__TOMMROC_HW_TEMPLATE_BUS_UART_DEF_AT_LEAST_ONE_LEUART_IS_USED__)
#include "main.h"
#if !defined (HAL_UART_MODULE_ENABLED) && !defined (HAL_USART_MODULE_ENABLED)
#error "HAL_UART_MODULE_ENABLED or HAL_USART_MODULE_ENABLED must be defined"
#endif
#endif

/*******************************************************************************
 * defines
 ******************************************************************************/
#if defined (__TOMMROC_HW_USE_UART_1_TEMPLATE__)
#if (defined (USART1_TX_Pin) && defined (USART1_TX_GPIO_Port) && defined (USART1_RX_Pin) && defined (USART1_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_PIN             (USART1_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_GPIO_PORT       (USART1_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_PIN             (USART1_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_GPIO_PORT       (USART1_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IRQn               (USART1_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_IS_USED
#elif (defined (USART1_TX_Pin) && defined (USART1_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_PIN             (USART1_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_GPIO_PORT       (USART1_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IRQn               (USART1_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_IS_USED
#elif (defined (USART1_RX_Pin) && defined (USART1_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_PIN             (USART1_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_GPIO_PORT       (USART1_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IRQn               (USART1_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_IS_USED
#elif (defined (UART1_TX_Pin) && defined (UART1_TX_GPIO_Port) && defined (UART1_RX_Pin) && defined (UART1_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_PIN             (UART1_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_GPIO_PORT       (UART1_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_PIN             (UART1_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_GPIO_PORT       (UART1_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IRQn               (UART1_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_IS_USED
#elif (defined (UART1_TX_Pin) && defined (UART1_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_PIN             (UART1_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_GPIO_PORT       (UART1_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IRQn               (UART1_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_TX_IS_USED
#elif (defined (UART1_RX_Pin) && defined (UART1_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_PIN             (UART1_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_GPIO_PORT       (UART1_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IRQn               (UART1_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RX_IS_USED
#else
#error "Define USART1_TX and/or USART1_RX Pin"
#endif
#if defined (TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_IS_USED)
#if (defined (USART1_DE_Pin) && defined (USART1_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_DE_PIN             (USART1_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_DE_GPIO_PORT       (USART1_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_DE_IS_USED
#elif (defined (UART1_DE_Pin) && defined (UART1_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_DE_PIN             (UART1_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_DE_GPIO_PORT       (UART1_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_DE_IS_USED
#elif (defined (USART1_RTS_Pin) && defined (USART1_RTS_GPIO_Port) && defined (USART1_CTS_Pin) && defined (USART1_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_PIN            (USART1_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_GPIO_PORT      (USART1_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_PIN            (USART1_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_GPIO_PORT      (USART1_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_IS_USED
#elif (defined (USART1_RTS_Pin) && defined (USART1_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_PIN            (USART1_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_GPIO_PORT      (USART1_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_IS_USED
#elif (defined (USART1_CTS_Pin) && defined (USART1_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_PIN            (USART1_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_GPIO_PORT      (USART1_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_IS_USED
#elif (defined (UART1_RTS_Pin) && defined (UART1_RTS_GPIO_Port) && defined (UART1_CTS_Pin) && defined (UART1_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_PIN            (UART1_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_GPIO_PORT      (UART1_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_PIN            (UART1_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_GPIO_PORT      (UART1_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_IS_USED
#elif (defined (UART1_RTS_Pin) && defined (UART1_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_PIN            (UART1_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_GPIO_PORT      (UART1_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_RTS_IS_USED
#elif (defined (UART1_CTS_Pin) && defined (UART1_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_PIN            (UART1_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_GPIO_PORT      (UART1_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART1_CTS_IS_USED
#endif
#endif
#endif

#if defined (__TOMMROC_HW_USE_UART_2_TEMPLATE__)
#if (defined (USART2_TX_Pin) && defined (USART2_TX_GPIO_Port) && defined (USART2_RX_Pin) && defined (USART2_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_PIN             (USART2_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_GPIO_PORT       (USART2_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_PIN             (USART2_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_GPIO_PORT       (USART2_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IRQn               (USART2_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_IS_USED
#elif (defined (USART2_TX_Pin) && defined (USART2_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_PIN             (USART2_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_GPIO_PORT       (USART2_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IRQn               (USART2_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_IS_USED
*elif (defined (USART2_RX_Pin) && defined (USART2_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_PIN             (USART2_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_GPIO_PORT       (USART2_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IRQn               (USART2_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_IS_USED
#elif (defined (UART2_TX_Pin) && defined (UART2_TX_GPIO_Port) && defined (UART2_RX_Pin) && defined (UART2_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_PIN             (UART2_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_GPIO_PORT       (UART2_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_PIN             (UART2_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_GPIO_PORT       (UART2_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IRQn               (UART2_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_IS_USED
#elif (defined (UART2_TX_Pin) && defined (UART2_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_PIN             (UART2_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_GPIO_PORT       (UART2_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IRQn               (UART2_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_TX_IS_USED
#elif (defined (UART2_RX_Pin) && defined (UART2_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_PIN             (UART2_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_GPIO_PORT       (UART2_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IRQn               (UART2_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RX_IS_USED
#else
#error "Define USART2_TX and/or USART2_RX Pin"
#endif
#if defined (TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_IS_USED)
#if (defined (USART2_DE_Pin) && defined (USART2_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_DE_PIN             (USART2_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_DE_GPIO_PORT       (USART2_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_DE_IS_USED
#elif (defined (UART2_DE_Pin) && defined (UART2_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_DE_PIN             (UART2_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_DE_GPIO_PORT       (UART2_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_DE_IS_USED
#elif (defined (USART2_RTS_Pin) && defined (USART2_RTS_GPIO_Port) && defined (USART2_CTS_Pin) && defined (USART2_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_PIN            (USART2_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_GPIO_PORT      (USART2_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_PIN            (USART2_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_GPIO_PORT      (USART2_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_IS_USED
#elif (defined (USART2_RTS_Pin) && defined (USART2_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_PIN            (USART2_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_GPIO_PORT      (USART2_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_IS_USED
#elif (defined (USART2_CTS_Pin) && defined (USART2_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_PIN            (USART2_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_GPIO_PORT      (USART2_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_IS_USED
#elif (defined (UART2_RTS_Pin) && defined (UART2_RTS_GPIO_Port) && defined (UART2_CTS_Pin) && defined (UART2_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_PIN            (UART2_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_GPIO_PORT      (UART2_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_PIN            (UART2_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_GPIO_PORT      (UART2_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_IS_USED
#elif (defined (UART2_RTS_Pin) && defined (UART2_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_PIN            (UART2_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_GPIO_PORT      (UART2_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_RTS_IS_USED
#elif (defined (UART2_CTS_Pin) && defined (UART2_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_PIN            (UART2_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_GPIO_PORT      (UART2_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART2_CTS_IS_USED
#endif
#endif
#endif

#if defined (__TOMMROC_HW_USE_UART_3_TEMPLATE__)
#if (defined (USART3_TX_Pin) && defined (USART3_TX_GPIO_Port) && defined (USART3_RX_Pin) && defined (USART3_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_PIN             (USART3_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_GPIO_PORT       (USART3_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_PIN             (USART3_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_GPIO_PORT       (USART3_RX_GPIO_Port)
#if !defined (__TOMMROC_TEMPLATE_ARM_STM32G0_IS_USED__)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IRQn               (USART3_IRQn)
#else
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IRQn               (USART3_4_LPUART1_IRQn)
#endif
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_IS_USED
#elif (defined (USART3_TX_Pin) && defined (USART3_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_PIN             (USART3_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_GPIO_PORT       (USART3_TX_GPIO_Port)
#if !defined (__TOMMROC_TEMPLATE_ARM_STM32G0_IS_USED__)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IRQn               (USART3_IRQn)
#else
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IRQn               (USART3_4_LPUART1_IRQn)
#endif
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_IS_USED
#elif (defined (USART3_RX_Pin) && defined (USART3_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_PIN             (USART3_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_GPIO_PORT       (USART3_RX_GPIO_Port)
#if !defined (__TOMMROC_TEMPLATE_ARM_STM32G0_IS_USED__)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IRQn               (USART3_IRQn)
#else
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IRQn               (USART3_4_LPUART1_IRQn)
#endif
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_IS_USED
#elif (defined (UART3_TX_Pin) && defined (UART3_TX_GPIO_Port) && defined (UART3_RX_Pin) && defined (UART3_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_PIN             (UART3_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_GPIO_PORT       (UART3_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_PIN             (UART3_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_GPIO_PORT       (UART3_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IRQn               (UART3_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_IS_USED
#elif (defined (UART3_TX_Pin) && defined (UART3_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_PIN             (UART3_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_GPIO_PORT       (UART3_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IRQn               (UART3_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_TX_IS_USED
#elif (defined (UART3_RX_Pin) && defined (UART3_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_PIN             (UART3_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_GPIO_PORT       (UART3_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IRQn               (UART3_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RX_IS_USED
#else
#error "Define USART3_TX and/or USART3_RX Pin"
#endif
#if defined (TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_IS_USED)
#if (defined (USART3_DE_Pin) && defined (USART3_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_DE_PIN             (USART3_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_DE_GPIO_PORT       (USART3_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_DE_IS_USED
#elif (defined (UART3_DE_Pin) && defined (UART3_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_DE_PIN             (UART3_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_DE_GPIO_PORT       (UART3_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_DE_IS_USED
#elif (defined (USART3_RTS_Pin) && defined (USART3_RTS_GPIO_Port) && defined (USART3_CTS_Pin) && defined (USART3_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_PIN            (USART3_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_GPIO_PORT      (USART3_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_PIN            (USART3_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_GPIO_PORT      (USART3_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_IS_USED
#elif (defined (USART3_RTS_Pin) && defined (USART3_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_PIN            (USART3_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_GPIO_PORT      (USART3_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_IS_USED
#elif (defined (USART3_CTS_Pin) && defined (USART3_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_PIN            (USART3_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_GPIO_PORT      (USART3_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_IS_USED
#elif (defined (UART3_RTS_Pin) && defined (UART3_RTS_GPIO_Port) && defined (UART3_CTS_Pin) && defined (UART3_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_PIN            (UART3_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_GPIO_PORT      (UART3_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_PIN            (UART3_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_GPIO_PORT      (UART3_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_IS_USED
#elif (defined (UART3_RTS_Pin) && defined (UART3_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_PIN            (UART3_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_GPIO_PORT      (UART3_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_RTS_IS_USED
#elif (defined (UART3_CTS_Pin) && defined (UART3_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_PIN            (UART3_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_GPIO_PORT      (UART3_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART3_CTS_IS_USED
#endif
#endif
#endif

#if defined (__TOMMROC_HW_USE_UART_4_TEMPLATE__)
#if (defined (USART4_TX_Pin) && defined (USART4_TX_GPIO_Port) && defined (USART4_RX_Pin) && defined (USART4_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_PIN             (USART4_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_GPIO_PORT       (USART4_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_PIN             (USART4_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_GPIO_PORT       (USART4_RX_GPIO_Port)
#if !defined (__TOMMROC_TEMPLATE_ARM_STM32G0_IS_USED__)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IRQn               (USART4_IRQn)
#else
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IRQn               (USART3_4_LPUART1_IRQn)
#endif
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_IS_USED
#elif (defined (USART4_TX_Pin) && defined (USART4_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_PIN             (USART4_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_GPIO_PORT       (USART4_TX_GPIO_Port)
#if !defined (__TOMMROC_TEMPLATE_ARM_STM32G0_IS_USED__)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IRQn               (USART4_IRQn)
#else
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IRQn               (USART3_4_LPUART1_IRQn)
#endif
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_IS_USED
#elif (defined (USART4_RX_Pin) && defined (USART4_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_PIN             (USART4_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_GPIO_PORT       (USART4_RX_GPIO_Port)
#if !defined (__TOMMROC_TEMPLATE_ARM_STM32G0_IS_USED__)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IRQn               (USART4_IRQn)
#else
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IRQn               (USART3_4_LPUART1_IRQn)
#endif
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_IS_USED
#elif (defined (UART4_TX_Pin) && defined (UART4_TX_GPIO_Port) && defined (UART4_RX_Pin) && defined (UART4_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_PIN             (UART4_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_GPIO_PORT       (UART4_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_PIN             (UART4_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_GPIO_PORT       (UART4_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IRQn               (UART4_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_IS_USED
#elif (defined (UART4_TX_Pin) && defined (UART4_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_PIN             (UART4_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_GPIO_PORT       (UART4_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IRQn               (UART4_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_TX_IS_USED
#elif (defined (UART4_RX_Pin) && defined (UART4_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_PIN             (UART4_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_GPIO_PORT       (UART4_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IRQn               (UART4_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RX_IS_USED
#else
#error "Define USART4_TX and/or USART4_RX Pin"
#endif
#if defined (TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_IS_USED)
#if (defined (USART4_DE_Pin) && defined (USART4_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_DE_PIN             (USART4_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_DE_GPIO_PORT       (USART4_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_DE_IS_USED
#elif (defined (UART4_DE_Pin) && defined (UART4_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_DE_PIN             (UART4_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_DE_GPIO_PORT       (UART4_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_DE_IS_USED
#elif (defined (USART4_RTS_Pin) && defined (USART4_RTS_GPIO_Port) && defined (USART4_CTS_Pin) && defined (USART4_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_PIN            (USART4_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_GPIO_PORT      (USART4_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_PIN            (USART4_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_GPIO_PORT      (USART4_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_IS_USED
#elif (defined (USART4_RTS_Pin) && defined (USART4_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_PIN            (USART4_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_GPIO_PORT      (USART4_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_IS_USED
#elif (defined (USART4_CTS_Pin) && defined (USART4_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_PIN            (USART4_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_GPIO_PORT      (USART4_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_IS_USED
#elif (defined (UART4_RTS_Pin) && defined (UART4_RTS_GPIO_Port) && defined (UART4_CTS_Pin) && defined (UART4_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_PIN            (UART4_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_GPIO_PORT      (UART4_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_PIN            (UART4_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_GPIO_PORT      (UART4_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_IS_USED
#elif (defined (UART4_RTS_Pin) && defined (UART4_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_PIN            (UART4_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_GPIO_PORT      (UART4_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_RTS_IS_USED
#elif (defined (UART4_CTS_Pin) && defined (UART4_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_PIN            (UART4_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_GPIO_PORT      (UART4_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART4_CTS_IS_USED
#endif
#endif
#endif

#if defined (__TOMMROC_HW_USE_UART_5_TEMPLATE__)
#if (defined (USART5_TX_Pin) && defined (USART5_TX_GPIO_Port) && defined (USART5_RX_Pin) && defined (USART5_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_PIN             (USART5_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_GPIO_PORT       (USART5_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_PIN             (USART5_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_GPIO_PORT       (USART5_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IRQn               (USART5_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_IS_USED
#elif (defined (USART5_TX_Pin) && defined (USART5_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_PIN             (USART5_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_GPIO_PORT       (USART5_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IRQn               (USART5_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_IS_USED
#elif (defined (USART5_RX_Pin) && defined (USART5_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_PIN             (USART5_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_GPIO_PORT       (USART5_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IRQn               (USART5_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_IS_USED
#elif (defined (UART5_TX_Pin) && defined (UART5_TX_GPIO_Port) && defined (UART5_RX_Pin) && defined (UART5_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_PIN             (UART5_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_GPIO_PORT       (UART5_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_PIN             (UART5_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_GPIO_PORT       (UART5_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IRQn               (UART5_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_IS_USED
#elif (defined (UART5_TX_Pin) && defined (UART5_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_PIN             (UART5_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_GPIO_PORT       (UART5_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IRQn               (UART5_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_TX_IS_USED
#elif (defined (UART5_RX_Pin) && defined (UART5_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_PIN             (UART5_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_GPIO_PORT       (UART5_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IRQn               (UART5_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RX_IS_USED
#else
#error "Define USART5_TX and/or USART5_RX Pin"
#endif
#if defined (TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_IS_USED)
#if (defined (USART5_DE_Pin) && defined (USART5_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_DE_PIN             (USART5_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_DE_GPIO_PORT       (USART5_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_DE_IS_USED
#elif (defined (UART5_DE_Pin) && defined (UART5_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_DE_PIN             (UART5_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_DE_GPIO_PORT       (UART5_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_DE_IS_USED
#elif (defined (USART5_RTS_Pin) && defined (USART5_RTS_GPIO_Port) && defined (USART5_CTS_Pin) && defined (USART5_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_PIN            (USART5_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_GPIO_PORT      (USART5_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_PIN            (USART5_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_GPIO_PORT      (USART5_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_IS_USED
#elif (defined (USART5_RTS_Pin) && defined (USART5_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_PIN            (USART5_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_GPIO_PORT      (USART5_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_IS_USED
#elif (defined (USART5_CTS_Pin) && defined (USART5_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_PIN            (USART5_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_GPIO_PORT      (USART5_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_IS_USED
#elif (defined (UART5_RTS_Pin) && defined (UART5_RTS_GPIO_Port) && defined (UART5_CTS_Pin) && defined (UART5_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_PIN            (UART5_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_GPIO_PORT      (UART5_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_PIN            (UART5_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_GPIO_PORT      (UART5_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_IS_USED
#elif (defined (UART5_RTS_Pin) && defined (UART5_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_PIN            (UART5_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_GPIO_PORT      (UART5_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_RTS_IS_USED
#elif (defined (UART5_CTS_Pin) && defined (UART5_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_PIN            (UART5_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_GPIO_PORT      (UART5_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART5_CTS_IS_USED
#endif
#endif
#endif

#if defined (__TOMMROC_HW_USE_UART_6_TEMPLATE__)
#if (defined (USART6_TX_Pin) && defined (USART6_TX_GPIO_Port) && defined (USART6_RX_Pin) && defined (USART6_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_PIN             (USART6_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_GPIO_PORT       (USART6_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_PIN             (USART6_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_GPIO_PORT       (USART6_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IRQn               (USART6_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_IS_USED
#elif (defined (USART6_TX_Pin) && defined (USART6_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_PIN             (USART6_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_GPIO_PORT       (USART6_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IRQn               (USART6_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_IS_USED
#elif (defined (USART6_RX_Pin) && defined (USART6_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_PIN             (USART6_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_GPIO_PORT       (USART6_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IRQn               (USART6_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_IS_USED
#elif (defined (UART6_TX_Pin) && defined (UART6_TX_GPIO_Port) && defined (UART6_RX_Pin) && defined (UART6_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_PIN             (UART6_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_GPIO_PORT       (UART6_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_PIN             (UART6_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_GPIO_PORT       (UART6_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IRQn               (UART6_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_IS_USED
#elif (defined (UART6_TX_Pin) && defined (UART6_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_PIN             (UART6_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_GPIO_PORT       (UART6_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IRQn               (UART6_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_TX_IS_USED
#elif (defined (UART6_RX_Pin) && defined (UART6_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_PIN             (UART6_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_GPIO_PORT       (UART6_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IRQn               (UART6_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RX_IS_USED
#else
#error "Define USART6_TX and/or USART6_RX Pin"
#endif
#if defined (TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_IS_USED)
#if (defined (USART6_DE_Pin) && defined (USART6_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_DE_PIN             (USART6_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_DE_GPIO_PORT       (USART6_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_DE_IS_USED
#elif (defined (UART6_DE_Pin) && defined (UART6_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_DE_PIN             (UART6_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_DE_GPIO_PORT       (UART6_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_DE_IS_USED
#elif (defined (USART6_RTS_Pin) && defined (USART6_RTS_GPIO_Port) && defined (USART6_CTS_Pin) && defined (USART6_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_PIN            (USART6_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_GPIO_PORT      (USART6_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_PIN            (USART6_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_GPIO_PORT      (USART6_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_IS_USED
#elif (defined (USART6_RTS_Pin) && defined (USART6_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_PIN            (USART6_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_GPIO_PORT      (USART6_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_IS_USED
#elif (defined (USART6_CTS_Pin) && defined (USART6_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_PIN            (USART6_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_GPIO_PORT      (USART6_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_IS_USED
#elif (defined (UART6_RTS_Pin) && defined (UART6_RTS_GPIO_Port) && defined (UART6_CTS_Pin) && defined (UART6_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_PIN            (UART6_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_GPIO_PORT      (UART6_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_PIN            (UART6_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_GPIO_PORT      (UART6_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_IS_USED
#elif (defined (UART6_RTS_Pin) && defined (UART6_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_PIN            (UART6_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_GPIO_PORT      (UART6_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_RTS_IS_USED
#elif (defined (UART6_CTS_Pin) && defined (UART6_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_PIN            (UART6_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_GPIO_PORT      (UART6_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART6_CTS_IS_USED
#endif
#endif
#endif

#if defined (__TOMMROC_HW_USE_UART_7_TEMPLATE__)
#if (defined (USART7_TX_Pin) && defined (USART7_TX_GPIO_Port) && defined (USART7_RX_Pin) && defined (USART7_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_PIN             (USART7_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_GPIO_PORT       (USART7_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_PIN             (USART7_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_GPIO_PORT       (USART7_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IRQn               (USART7_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_IS_USED
#elif (defined (USART7_TX_Pin) && defined (USART7_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_PIN             (USART7_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_GPIO_PORT       (USART7_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IRQn               (USART7_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_IS_USED
#elif (defined (USART7_RX_Pin) && defined (USART7_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_PIN             (USART7_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_GPIO_PORT       (USART7_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IRQn               (USART7_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_IS_USED
#elif (defined (UART7_TX_Pin) && defined (UART7_TX_GPIO_Port) && defined (UART7_RX_Pin) && defined (UART7_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_PIN             (UART7_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_GPIO_PORT       (UART7_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_PIN             (UART7_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_GPIO_PORT       (UART7_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IRQn               (UART7_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_IS_USED
#elif (defined (UART7_TX_Pin) && defined (UART7_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_PIN             (UART7_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_GPIO_PORT       (UART7_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IRQn               (UART7_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_TX_IS_USED
#elif (defined (UART7_RX_Pin) && defined (UART7_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_PIN             (UART7_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_GPIO_PORT       (UART7_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IRQn               (UART7_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RX_IS_USED
#else
#error "Define USART7_TX and/or USART7_RX Pin"
#endif
#if defined (TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_IS_USED)
#if (defined (USART7_DE_Pin) && defined (USART7_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_DE_PIN             (USART7_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_DE_GPIO_PORT       (USART7_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_DE_IS_USED
#elif (defined (UART7_DE_Pin) && defined (UART7_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_DE_PIN             (UART7_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_DE_GPIO_PORT       (UART7_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_DE_IS_USED
#elif (defined (USART7_RTS_Pin) && defined (USART7_RTS_GPIO_Port) && defined (USART7_CTS_Pin) && defined (USART7_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_PIN            (USART7_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_GPIO_PORT      (USART7_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_PIN            (USART7_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_GPIO_PORT      (USART7_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_IS_USED
#elif (defined (USART7_RTS_Pin) && defined (USART7_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_PIN            (USART7_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_GPIO_PORT      (USART7_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_IS_USED
#elif (defined (USART7_CTS_Pin) && defined (USART7_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_PIN            (USART7_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_GPIO_PORT      (USART7_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_IS_USED
#elif (defined (UART7_RTS_Pin) && defined (UART7_RTS_GPIO_Port) && defined (UART7_CTS_Pin) && defined (UART7_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_PIN            (UART7_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_GPIO_PORT      (UART7_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_PIN            (UART7_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_GPIO_PORT      (UART7_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_IS_USED
#elif (defined (UART7_RTS_Pin) && defined (UART7_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_PIN            (UART7_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_GPIO_PORT      (UART7_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_RTS_IS_USED
#elif (defined (UART7_CTS_Pin) && defined (UART7_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_PIN            (UART7_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_GPIO_PORT      (UART7_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART7_CTS_IS_USED
#endif
#endif
#endif

#if defined (__TOMMROC_HW_USE_UART_8_TEMPLATE__)
#if (defined (USART8_TX_Pin) && defined (USART8_TX_GPIO_Port) && defined (USART8_RX_Pin) && defined (USART8_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_PIN             (USART8_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_GPIO_PORT       (USART8_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_PIN             (USART8_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_GPIO_PORT       (USART8_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IRQn               (USART8_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_IS_USED
#elif (defined (USART8_TX_Pin) && defined (USART8_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_PIN             (USART8_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_GPIO_PORT       (USART8_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IRQn               (USART8_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_IS_USED
#elif (defined (USART8_RX_Pin) && defined (USART8_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_PIN             (USART8_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_GPIO_PORT       (USART8_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IRQn               (USART8_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_IS_USED
#elif (defined (UART8_TX_Pin) && defined (UART8_TX_GPIO_Port) && defined (UART8_RX_Pin) && defined (UART8_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_PIN             (UART8_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_GPIO_PORT       (UART8_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_PIN             (UART8_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_GPIO_PORT       (UART8_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IRQn               (UART8_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_IS_USED
#elif (defined (UART8_TX_Pin) && defined (UART8_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_PIN             (UART8_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_GPIO_PORT       (UART8_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IRQn               (UART8_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_TX_IS_USED
#elif (defined (UART8_RX_Pin) && defined (UART8_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_PIN             (UART8_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_GPIO_PORT       (UART8_RX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IRQn               (UART8_IRQn)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RX_IS_USED
#else
#error "Define USART8_TX and/or USART8_RX Pin"
#endif
#if defined (TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_IS_USED)
#if (defined (USART8_DE_Pin) && defined (USART8_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_DE_PIN             (USART8_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_DE_GPIO_PORT       (USART8_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_DE_IS_USED
#elif (defined (UART8_DE_Pin) && defined (UART8_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_DE_PIN             (UART8_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_DE_GPIO_PORT       (UART8_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_DE_IS_USED
#elif (defined (USART8_RTS_Pin) && defined (USART8_RTS_GPIO_Port) && defined (USART8_CTS_Pin) && defined (USART8_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_PIN            (USART8_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_GPIO_PORT      (USART8_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_PIN            (USART8_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_GPIO_PORT      (USART8_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_IS_USED
#elif (defined (USART8_RTS_Pin) && defined (USART8_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_PIN            (USART8_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_GPIO_PORT      (USART8_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_IS_USED
#elif (defined (USART8_CTS_Pin) && defined (USART8_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_PIN            (USART8_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_GPIO_PORT      (USART8_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_IS_USED
#elif (defined (UART8_RTS_Pin) && defined (UART8_RTS_GPIO_Port) && defined (UART8_CTS_Pin) && defined (UART8_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_PIN            (UART8_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_GPIO_PORT      (UART8_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_PIN            (UART8_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_GPIO_PORT      (UART8_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_IS_USED
#elif (defined (UART8_RTS_Pin) && defined (UART8_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_PIN            (UART8_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_GPIO_PORT      (UART8_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_RTS_IS_USED
#elif (defined (UART8_CTS_Pin) && defined (UART8_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_PIN            (UART8_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_GPIO_PORT      (UART8_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_UART8_CTS_IS_USED
#endif
#endif
#endif

#if defined (__TOMMROC_HW_USE_LEUART_1_TEMPLATE__)
#if (defined (LPUART1_TX_Pin) && defined (LPUART1_TX_GPIO_Port) && defined (LPUART1_RX_Pin) && defined (LPUART1_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_TX_PIN           (LPUART1_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_TX_GPIO_PORT     (LPUART1_TX_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RX_PIN           (LPUART1_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RX_GPIO_PORT     (LPUART1_RX_GPIO_Port)
#if !defined (__TOMMROC_TEMPLATE_ARM_STM32G0_IS_USED__)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_IRQn             (LPUART1_IRQn)
#else
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_IRQn             (USART3_4_LPUART1_IRQn)
#endif
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_TX_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RX_IS_USED
#elif (defined (LPUART1_TX_Pin) && defined (LPUART1_TX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_TX_PIN           (LPUART1_TX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_TX_GPIO_PORT     (LPUART1_TX_GPIO_Port)
#if !defined (__TOMMROC_TEMPLATE_ARM_STM32G0_IS_USED__)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_IRQn             (LPUART1_IRQn)
#else
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_IRQn             (USART3_4_LPUART1_IRQn)
#endif
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_TX_IS_USED
#elif (defined (LPUART1_RX_Pin) && defined (LPUART1_RX_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RX_PIN           (LPUART1_RX_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RX_GPIO_PORT     (LPUART1_RX_GPIO_Port)
#if !defined (__TOMMROC_TEMPLATE_ARM_STM32G0_IS_USED__)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_IRQn             (LPUART1_IRQn)
#else
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_IRQn             (USART3_4_LPUART1_IRQn)
#endif
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RX_IS_USED
#else
#error "Define LPUART1_TX and/or LPUART1_RX Pin"
#endif
#if defined (TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_IS_USED)
#if (defined (LPUART1_DE_Pin) && defined (LPUART1_DE_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_DE_PIN           (LPUART1_DE_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_DE_GPIO_PORT     (LPUART1_DE_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RS485_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_DE_IS_USED
#elif (defined (LPUART1_RTS_Pin) && defined (LPUART1_RTS_GPIO_Port) && defined (LPUART1_CTS_Pin) && defined (LPUART1_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RTS_PIN          (LPUART1_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RTS_GPIO_PORT    (LPUART1_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_CTS_PIN          (LPUART1_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_CTS_GPIO_PORT    (LPUART1_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RTS_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_CTS_IS_USED
#elif (defined (LPUART1_RTS_Pin) && defined (LPUART1_RTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RTS_PIN          (LPUART1_RTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RTS_GPIO_PORT    (LPUART1_RTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_RTS_IS_USED
#elif (defined (LPUART1_CTS_Pin) && defined (LPUART1_CTS_GPIO_Port))
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_CTS_PIN          (LPUART1_CTS_Pin)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_CTS_GPIO_PORT    (LPUART1_CTS_GPIO_Port)
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_HWCONTROL_IS_USED
#define TOMMROC_HW_TEMPLATE_BUS_UART_STM32_DEF_LPUART1_CTS_IS_USED
#endif
#endif
#endif

/*******************************************************************************
 * typedefs
 ******************************************************************************/

/*******************************************************************************
 * functions
 ******************************************************************************/

#endif

#endif

#endif
